# Build options
android.enableBuildScriptClasspathCheck=false
android.nonTransitiveRClass=true
android.useAndroidX=true
android.enableR8.fullMode=true
android.r8.strictFullModeForKeepRules=true
android.r8.optimizedResourceShrinking=true
android.newDsl=true
kotlin.code.style=official
kotlin.incremental.usePreciseJavaTracking=true
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# POM
GROUP=io.github.crow-misia.libyuv
POM_ARTIFACT_ID=libyuv-android
VERSION_NAME=0.43.2

POM_NAME=libyuv-android
POM_DESCRIPTION=LibYuv for Android
POM_URL=https://github.com/crow-misia/libyuv-android/

POM_LICENSE_NAME=Apache-2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/crow-misia/libyuv-android/
POM_SCM_CONNECTION=scm:git:git://github.com/crow-misia/libyuv-android.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/crow-misia/libyuv-android.git

POM_DEVELOPER_ID=crow-misia
POM_DEVELOPER_NAME=Zenichi Amano
POM_DEVELOPER_EMAIL=crow.misia@gmail.com

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
