# Build options
android.enableBuildScriptClasspathCheck=false
android.nonTransitiveRClass=true
android.useAndroidX=true
android.enableR8.fullMode=true
android.r8.strictFullModeForKeepRules=true
android.r8.optimizedResourceShrinking=true
android.newDsl=true
kotlin.code.style=official
kotlin.incremental.usePreciseJavaTracking=true
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
