[tools]
gitleaks = "latest"
lefthook = "latest"
node = "26"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
"pipx:bumpver" = "latest"
python = "latest"
uv = "latest"
