name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ['main']

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        java-version: [17]

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          dependency-graph: generate-and-submit

      - name: Check
        run: ./gradlew check
